#!/bin/sh

./coffeecoffee test/binary_search.coffee
./coffeecoffee test/binary_search2.coffee
./coffeecoffee test/bubble_sort.coffee
./coffeecoffee test/cubes.coffee
./coffeecoffee test/echo.coffee hello world
./coffeecoffee test/fib.coffee 15
./coffeecoffee test/linked_list.coffee
./coffeecoffee test/luhn_algorithm.coffee
./coffeecoffee test/merge_sort.coffee
./coffeecoffee test/quicksort_runtime.coffee
./coffeecoffee test/regular_expression_matcher.coffee
./coffeecoffee test/selection_sort.coffee
./coffeecoffee test/snippets.coffee

